[build]
  command = "npm install --legacy-peer-deps && npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/getDataZIM"
  to = "/.netlify/functions/lambda"
  status = 200
