[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "data"  # Carpeta que contiene tus archivos estáticos

[functions]
  directory = "netlify/functions/lambda.js"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline';
      style-src 'self' 'unsafe-inline';
      font-src 'self';
      img-src 'self';
      frame-src 'self';
      report-uri /csp-violation-report-endpoint
    """
