service: my-service

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  myLambdaFunction:
    handler: lambda/myLambdaFunction.handler
    events:
      - http:
          path: lambda-path
          method: get

  server:
    handler: server/server.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline
